easy_admin:
    site_name: 'ICUhelp'

    design:
        form_theme:
            - '@EasyAdmin/form/bootstrap_4.html.twig'
            - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
        menu:
            - { entity: 'User', label: 'link.users', icon: 'users' }
            - { entity: 'Snippet', label: 'link.snippets', icon: 'clipboard' }
            - { entity: 'SnippetCategory', label: 'link.snippet.category' }
            - { label: 'link.frontend', icon: 'power-off', route: 'homepage' }

    user:
        display_name: true
        display_avatar: false
        name_property_path: username

    entities:
        User:
            class: App\Entity\User
            label: label.user
            list:
                title: link.users
                fields:
                    - { property: 'id', label: 'label.id' }
                    - { property: 'username', label: 'label.username' }
                    - { property: 'email', type: 'email', label: 'label.email' }
            form:
                form_options: { validation_groups: ['Default'] }
                fields:
                    - { type: 'group', css_class: 'col-sm-7', label: 'title.user_basics' }
                    - { property: 'username', label: 'label.username' }
                    - { property: 'email', type: 'email', label: 'label.email' }
                    - { property: 'plainPassword', type: 'password', label: 'label.password', type_options: { required: false, empty_data: '' } }
                    - { type: 'group', css_class: 'col-sm-5', label: 'title.user_properties' }
                    - { property: 'roles', type: 'choice', label: 'label.roles', type_options: { multiple: true, choices: { 'ROLE_USER': 'ROLE_USER', 'ROLE_ADMIN': 'ROLE_ADMIN' } } }
                new:
                    title: 'title.user_new'
                    form_options: { validation_groups: ['Default', 'registration'] }
                edit:
                    title: 'title.user_edit'
        Snippet:
            class: App\Entity\Snippet
            label: label.snippet
            list:
                title: link.snippets
                fields:
                    - { property: 'id', label: 'label.id' }
                    - { property: 'name', label: 'label.snippet.name' }
                    - { property: 'category', label: 'label.snippet.category' }
            form:
                fields:
                    - { property: 'name', label: 'label.snippet.name' }
                    - { property: 'category', label: 'label.snippet.category' }
                    - { property: 'text', label: 'label.snippet.text', type: 'fos_ckeditor', type_options: { config_name: 'snippets' } }
                new:
                    title: 'title.snippet.new'
                edit:
                    title: 'title.snippet.edit'
        SnippetCategory:
            class: App\Entity\SnippetCategory
            label: label.snippet.category
            list:
                title: link.snippet.category
                fields:
                    - { property: 'id', label: 'label.id' }
                    - { property: 'name', label: 'label.snippet.category.name' }
                    - { property: 'priority', label: 'label.snippet.category.priority' }
            form:
                fields:
                    - { property: 'id', label: 'label.id' }
                    - { property: 'name', label: 'label.snippet.category.name' }
                    - { property: 'priority', label: 'label.snippet.category.priority' }
                new:
                    title: 'title.snippet.category.new'
                edit:
                    title: 'title.snippet.category.edit'