easy_admin:
    site_name: 'ICUhelp backend'

    user:
        display_name: true
        display_avatar: false
        name_property_path: username

    entities:
        User:
            class: App\Entity\User