name: app

type: php:7.4

runtime:
    extensions:
        - apcu
        - mbstring
        - sodium
        - iconv
        - ctype
        - xsl

relationships:
    database: "db:mysql"

build:
    flavor: none

web:
    locations:
        "/":
            root: "public"
            expires: 1h
            passthru: "/index.php"

disk: 1024

mounts:
    "/var": { source: local, source_path: var }
    '/var/storage/uploads': { source: local, source_path: uploads }

hooks:
    build: |
        set -x -e

        curl -s https://get.symfony.com/cloud/configurator | (>&2 bash)
        (>&2 symfony-build)

    deploy: |
        set -x -e

        mkdir -p public/uploads
        (>&2 symfony-deploy)
