name: app

type: php:7.4

runtime:
    extensions:
        - apcu
        - mbstring
        - sodium
        - iconv
        - ctype
        - xsl

relationships:
    database: "db:mysql"

build:
    flavor: none

web:
    locations:
        "/":
            root: "public"
            expires: 1h
            passthru: "/index.php"
        '/uploads':
            root: 'public/uploads'
            scripts: false
            allow: false
                rules:
                    # Only allow some static files.
                    '\.(jpe?g|png|gif|svgz?|pdf|doc|docx)$':
                        allow: true

disk: 512

mounts:
    "/var": { source: local, source_path: var }
    '/public/uploads': { source: local, source_path: uploads }

hooks:
    build: |
        set -x -e

        curl -s https://get.symfony.com/cloud/configurator | (>&2 bash)
        (>&2 symfony-build)

    deploy: |
        set -x -e

        mkdir -p public/uploads
        (>&2 symfony-deploy)
