# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    default_admin_email: noreply@icuhelp.com
    default_admin_email_name: 'ICUhelp Mail Bot'
    upload_directory: '%kernel.project_dir%/public/uploads/'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $adminEmail: "%env(string:default:default_admin_email:ADMIN_EMAIL)%"
            $adminEmailName: "%env(string:default:default_admin_email_name:ADMIN_EMAIL_NAME)%"

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\EventListener\UniqueSOPTagListener:
        tags:
            - { name: doctrine.event_listener, event: 'prePersist' }
            - { name: doctrine.event_listener, event: 'preUpdate' }

    App\EventListener\UserActivationListener:
        tags:
            - { name: kernel.event_listener, event: kernel.request }

    App\EventSubscriber\HashPasswordSubsciber:
        tags:
            - { name: 'doctrine.event_subscriber' }

    App\Form\SOPType:
        arguments: [ "@doctrine.orm.entity_manager" ]
        tags:
            - { name: form.type }

    App\Service\FileUploader:
        arguments:
            $targetDirectory: '%upload_directory%'

    Symfony\Bridge\Doctrine\Security\RememberMe\DoctrineTokenProvider: ~
